# -----
# This YAML describes the FINRA workflow for TLess in Knative.
#
# See here for more details on the workflow:
# https://github.com/faasm/experiment-tless/blob/main/workflows/finra/README.md
# -----
apiVersion: messaging.knative.dev/v1
kind: Channel
metadata:
  name: ingress-to-fetch-public
  namespace: tless
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
---
apiVersion: messaging.knative.dev/v1
kind: Channel
metadata:
  name: ingress-to-fetch-private
  namespace: tless
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
---
apiVersion: messaging.knative.dev/v1
kind: Channel
metadata:
  name: fetch-to-audit
  namespace: tless
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
---
apiVersion: messaging.knative.dev/v1
kind: Channel
metadata:
  name: audit-to-merge
  namespace: tless
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: finra-fetch-public
  namespace: tless
spec:
  template:
    spec:
      runtimeClassName: ${RUNTIME_CLASS_NAME}
      containers:
        - image: ghcr.io/coco-serverless/tless-knative-worker:${TLESS_VERSION}
          ports:
            - containerPort: 8080
          workingDir: /code/faasm-examples/workflows/finra/knative
          command: [ "./target/release/tless-cloudevent-handler" ]
    metadata:
      labels:
        tless.workflows/name: finra-fetch-public
      annotations:
        # NOTE: we may have to enable this annotation in Kata's config file
        # under hypervisor.qemu.enable_annotations (add 'default_memory')
        io.katacontainers.config.hypervisor.default_memory: "6144"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: finra-fetch-private
  namespace: tless
spec:
  template:
    spec:
      runtimeClassName: ${RUNTIME_CLASS_NAME}
      containers:
        - image: ghcr.io/coco-serverless/tless-knative-worker:${TLESS_VERSION}
          ports:
            - containerPort: 8080
          workingDir: /code/faasm-examples/workflows/finra/knative
          command: [ "./target/release/tless-cloudevent-handler" ]
    metadata:
      labels:
        tless.workflows/name: finra-fetch-private
      annotations:
        # NOTE: we may have to enable this annotation in Kata's config file
        # under hypervisor.qemu.enable_annotations (add 'default_memory')
        io.katacontainers.config.hypervisor.default_memory: "6144"
---
apiVersion: sinks.knative.dev/v1alpha1
kind: JobSink
metadata:
  name: finra-audit
  namespace: tless
spec:
  job:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 4
      # Clean-up jobs once they are finished
      ttlSecondsAfterFinished: 30
      template:
        spec:
          runtimeClassName: ${RUNTIME_CLASS_NAME}
          restartPolicy: Never
          containers:
            - name: main
              # TODO: pin to version
              # image: ghcr.io/coco-serverless/tless-knative-worker:${TLESS_VERSION}
              image: ghcr.io/coco-serverless/tless-knative-worker@sha256:9e9adb7f6f2ce311b658383a8e4ffd725e00dfbb742b8343f4088fc038a87652
              ports:
                - containerPort: 8080
              workingDir: /code/faasm-examples/workflows/finra/knative
              command: [ "./target/release/tless-cloudevent-handler" ]
              env:
                - name: CE_FROM_FILE
                  value: "on"
        metadata:
          labels:
            tless.workflows/name: finra-audit
          annotations:
            # NOTE: we may have to enable this annotation in Kata's config file
            # under hypervisor.qemu.enable_annotations (add 'default_memory')
            io.katacontainers.config.hypervisor.default_memory: "6144"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: finra-merge
  namespace: tless
spec:
  template:
    spec:
      runtimeClassName: ${RUNTIME_CLASS_NAME}
      containers:
        - image: ghcr.io/coco-serverless/tless-knative-worker:${TLESS_VERSION}
          ports:
            - containerPort: 8080
          workingDir: /code/faasm-examples/finra/finra/knative
          command: [ "./target/release/tless-cloudevent-handler" ]
    metadata:
      labels:
        tless.workflows/name: finra-merge
      annotations:
        # High grace-period to guarantee the same instance processes requests
        # for all jobs in the JobSink (i.e. instances of the audit function)
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1m"
        # NOTE: we may have to enable this annotation in Kata's config file
        # under hypervisor.qemu.enable_annotations (add 'default_memory')
        io.katacontainers.config.hypervisor.default_memory: "6144"
---
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: edge-one-subscription
  namespace: tless
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: ingress-to-fetch-public
  reply:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: InMemoryChannel
      name: fetch-to-audit
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: finra-fetch-public
---
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: edge-two-subscription
  namespace: tless
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: ingress-to-fetch-private
  reply:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: InMemoryChannel
      name: fetch-to-audit
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: finra-fetch-private
---
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: edge-three-subscription
  namespace: tless
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: fetch-to-audit
  subscriber:
    ref:
      apiVersion: sinks.knative.dev/v1alpha1
      kind: JobSink
      name: finra-audit
---
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: edge-four-subscription
  namespace: tless
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: audit-to-merge
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: finra-merge
---
